# Generated by Django 3.0.3 on 2020-07-27 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_auto_20200722_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'address_type',
                    models.CharField(choices=[('blling', 'Billing'), ('shipping', 'Shipping')], max_length=120)
                ),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='Taiwan', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                (
                    'billing_profile',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')
                ),
            ],
        ),
    ]
