# Generated by Django 3.0.3 on 2020-08-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20200815_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
