# Generated by Django 3.0.3 on 2020-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_charge_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='card_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
