# Generated by Django 3.0.3 on 2020-09-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200908_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchaseManager',
        ),
    ]
