# Generated by Django 3.0.3 on 2020-09-18 07:16

from django.db import migrations, models
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200917_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'),
                upload_to=products.models.upload_product_file_location
            ),
        ),
    ]
