# Generated by Django 3.0.3 on 2020-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
